[package]
name = "planetary"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
serde = "1.0.228"

units = { path = "../units" }

[dev-dependencies]
approx = "0.5.1"
rand_chacha = "0.9.0"
